collections:
  authors:
    output: true
# default is set by scope - values pair
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "authors" # pages, posts, drafts or collections
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      #layout: "default"
      layout: "home" # this turn on the 'minima'

title: HUzzii
email: support@huzzii.com
description: >- # this means to ignore newlines until "baseurl:" for Google search & RSS feed description
  HUzzii Official Web
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
