collections:
  products:
    output: true
# default is set by scope - values pair
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "products" # pages, posts, drafts or collections
    values:
      #layout: "author"
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      #layout: "post"
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
      #layout: "home" # this turn on the 'minima'

title: HUzzii
logo: ../assets/img/huzzii-logo-1024x512-transparent.png
email: support@huzzii.com
description: >- # this means to ignore newlines until "baseurl:" for Google search & RSS feed description
  We love Tech, any of it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
show_downloads: false # github pages-themes to show download or not
#google_analytics: [Your Google Analytics tracking ID]
github:
  - is_project_page: false
  - is_user_page: false

# Build settings
#theme: minima
#remote_theme: pages-themes/merlot@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
